# Generated by Django 3.1.6 on 2021-02-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='idade',
            new_name='age',
        ),
    ]
